# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fe48b15a8c1430e71403e2f81b11618fa4d8f3928d8e52c7149e23597400f6e1fa4f41e813882baec1e6de466b949f33b73675be71ab0822ef3fc0366f81b7f

test:
  secret_key_base: 652c0dd2df3e9670620b092193a7bc39c4a11c7b971d596da291ae72f9b986d1071803bfc755a0cb5b4212e31cd84ccd8a19eb1de6c8ba4392e35e7b811c1f5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
